
# Site settings
url: https://screwdriver.cd
title: screwdriver.cd
# email: your-email@domain.com
# description:

social:
  - title: slack
    url: http://slack.screwdriver.cd
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/screwdriver-cd
  - title: github
    url: http://github.com/screwdriver-cd
  - title: tumblr
    url: http://blog.screwdriver.cd

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - screwdriver.yaml
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - Rakefile
  - ci
