
# Site settings
url: http://screwdriver.cd
title: screwdriver.cd
analytics: UA-88158708-2

social:
  - title: slack
    url: http://slack.screwdriver.cd
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/screwdriver-cd
  - title: github
    url: http://github.com/screwdriver-cd
  - title: tumblr
    url: http://blog.screwdriver.cd

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - screwdriver.yaml
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - Rakefile
  - ci
  - deploy.sh


# Team names, titles and social links
people:
- name: Jithin Emmanuel
  pic: jithin1987
  position: RESTafarian
  github: https://github.com/jithin1987

- name: St. John Johnson
  pic: stjohn
  position: Galactic Hitchhiker
  github: https://github.com/stjohnjohnson

- name: Tiffany Kyi
  pic: tkyi
  position: Turtle Addict
  github: https://github.com/tkyi

- name: Dao Lam
  pic: d2lam
  position: D2
  github: https://github.com/d2lam

- name: Darren Matsumoto
  pic: FenrirUnbound
  position: Blue Shell Connoisseur
  github: https://github.com/FenrirUnbound

- name: Peter Peterson
  pic: petey
  position: Javascript Jedi
  github: https://github.com/petey

- name: Reetika Rastogi
  pic: r3rastogi
  position: Untitled, 2017
  github: https://github.com/r3rastogi

- name: Jeremiah Wuenschel
  pic: jer
  position: Digital Plumber
  github: https://github.com/jer

- name: Min Zhang
  pic: minz1027
  position: Not Max
  github: https://github.com/minz1027
