workflow:
    - publish

shared:
    image: ruby:2

jobs:
    main:
        steps:
            - init: bundle install
            - doctor: bundle exec rake doctor
            - build: bundle exec rake build

    publish:
        steps:
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - setup-git: ./ci/git-ssh.sh
            - init: bundle install
            - publish: bundle exec rake publish
        secrets:
            # Pushing code to Git
            - GIT_KEY
